In [2]:
import numpy as np
import nnfs

from nnfs.datasets import spiral_data

nnfs.init()

X = [[1,2,3,2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7,3.3,-0.8]]


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
       self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
       self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward (self, inputs):
        self.output = np.maximum(0, inputs)
        
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities 
        #-np.max(inputs) would be a mistake 
        #it would be subtracting the highest value of outputs as inputs are the outputs right now

X, y = spiral_data(samples=100, classes=3)

#sample input of 2 values 
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

#a "batch" of 300
#input of 2 values this output is each neuron value of those 2 values
#this continues to repeat and this output are the first 5
#due to everything being initialised randomly so the distribution of predictions is also random
#a 1/3 prediction or close to it of everything
#now this model needs to be trained
#the next thing is to find out how right and wrong the output is with a loss function

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]
