In [9]:
import numpy as np
import nnfs 

nnfs.init()

layer_outputs = [[4.8, 1.21, 2.385],
                [8.9, -1.81, 0.2],
                [1.41, 1.051, 0.026]]

#to exponentiate the layer output values
#changes negative values to positive values without loosing there meaning 
exp_values =np.exp(layer_outputs)
#the sum of columns 
#print(np.sum(layer_outputs, axis=0))
#the sum os the rows
#print(np.sum(layer_outputs, axis=1))
#dividing the matrix of exponential values and make sure the right values line up
#a matrix of the same dimensions
#print(np.sum(layer_outputs, axis=1,keepdims=True))
    
#normalising the values
#y = u/epsilon n i=1 ui

norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True )
#prints normalised values
print(norm_values)

#print(sum(norm_values))

#the first list is the expontentiated values
#the second list is the normalised exponentiated values 
#the last output is a sum that shows they all add up to almost 1

#exponential values means that it doesnt take long to get exponential values and it does not take long to reach an overflow
#overflow prevention v = u - max(u)this subtracts the largest value in that layer from all of the values in that layer before exponentiation 
#the largest value will be a 0 and everything else will be less than 0
#the range of values is now (0, 1) on the y axis and (-infinity,0) on the x axis
#if there is 2 output layers and 1 the max is not subtracted from and 1 the max is subtracted from the outputs will be the same
#subtracting the max stops there being an overflow 

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


Input->Exponentiate->Normalise->output
Input-> (the combination of Exponentiate->Normalisation = Softmax)->Output
Input->Softmax activation function->Output 
softmax activation function equation